<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="5.1760" tests="4" failures="1">
  <testsuite name="Root Suite" timestamp="2021-03-03T19:37:18" tests="0" file="cypress/integration/user/workspace.spec.ts" time="0.0000" failures="0">
  </testsuite>
  <testsuite name="User workspace" timestamp="2021-03-03T19:37:18" tests="4" time="5.1760" failures="1">
    <testcase name="User workspace Should go to audit log" time="0.0000" classname="Should go to audit log">
      <failure message="Timed out retrying after 4050ms: `cy.click()` failed because this element is detached from the DOM.

`&lt;span class=&quot;nav-label&quot;&gt;Audit logs&lt;/span&gt;`

Cypress requires elements be attached in the DOM to interact with them.

The previous command that ran was:

  &gt; `cy.contains()`

This DOM element likely became detached somewhere between the previous and current command.

Common situations why this happens:
  - Your JS framework re-rendered asynchronously
  - Your app code reacted to an event firing and removed the element

You typically need to re-query for the element or add &apos;guards&apos; which delay Cypress from running new commands.

https://on.cypress.io/element-has-detached-from-dom" type="CypressError"><![CDATA[CypressError: Timed out retrying after 4050ms: `cy.click()` failed because this element is detached from the DOM.

`<span class="nav-label">Audit logs</span>`

Cypress requires elements be attached in the DOM to interact with them.

The previous command that ran was:

  > `cy.contains()`

This DOM element likely became detached somewhere between the previous and current command.

Common situations why this happens:
  - Your JS framework re-rendered asynchronously
  - Your app code reacted to an event firing and removed the element

You typically need to re-query for the element or add 'guards' which delay Cypress from running new commands.

https://on.cypress.io/element-has-detached-from-dom
    at $Cy.ensureAttached (http://localhost:8001/__cypress/runner/cypress_runner.js:161278:24)
    at runAllChecks (http://localhost:8001/__cypress/runner/cypress_runner.js:150123:12)
    at retryActionability (http://localhost:8001/__cypress/runner/cypress_runner.js:150195:16)
    at tryCatcher (http://localhost:8001/__cypress/runner/cypress_runner.js:10584:23)
    at Function.Promise.attempt.Promise.try (http://localhost:8001/__cypress/runner/cypress_runner.js:7858:29)
    at tryFn (http://localhost:8001/__cypress/runner/cypress_runner.js:165754:21)
    at whenStable (http://localhost:8001/__cypress/runner/cypress_runner.js:165792:12)
    at http://localhost:8001/__cypress/runner/cypress_runner.js:165287:16
    at tryCatcher (http://localhost:8001/__cypress/runner/cypress_runner.js:10584:23)
    at Promise._settlePromiseFromHandler (http://localhost:8001/__cypress/runner/cypress_runner.js:8519:31)
    at Promise._settlePromise (http://localhost:8001/__cypress/runner/cypress_runner.js:8576:18)
    at Promise._settlePromise0 (http://localhost:8001/__cypress/runner/cypress_runner.js:8621:10)
    at Promise._settlePromises (http://localhost:8001/__cypress/runner/cypress_runner.js:8701:18)
    at Promise._fulfill (http://localhost:8001/__cypress/runner/cypress_runner.js:8645:18)
    at http://localhost:8001/__cypress/runner/cypress_runner.js:10259:46
From Your Spec Code:
    at Context.eval (http://localhost:8001/__cypress/tests?p=cypress/integration/user/workspace.spec.ts:101:44)]]></failure>
    </testcase>
    <testcase name="User workspace Should go to SSH keys list" time="2.0480" classname="Should go to SSH keys list">
    </testcase>
    <testcase name="User workspace Should go to notifications list" time="1.6150" classname="Should go to notifications list">
    </testcase>
    <testcase name="User workspace Should go to manage user tab" time="1.5130" classname="Should go to manage user tab">
    </testcase>
  </testsuite>
</testsuites>